### PR TITLE
Correct post requests so that the order of keys doesn't matter

### PR DESCRIPTION
**Pull request by callumu21**
1. Corrected code so that the order of keys on the request body doesn't matter for post requests

### CODE REVIEW

**Review by BrennB99 — APPROVED** [review]
Nice one!

**Review by MattArwenLangham — APPROVED** [review]
Looks good!

**Review by Nosajthe1 — APPROVED** [review]
Nice one Cal!!

**Review by wbaig2 — APPROVED** [review]
Looks great!

**Pull request merged**
